{% set name = "numpy" %}
{% set version = "1.14.2" %}
{% set sha256 = "facc6f925c3099ac01a1f03758100772560a0b020fb9d70f210404be08006bcb" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    # patches for MKL based enhancements
    - intel_mkl-version.patch # [not nomkl]
    - intel_use_mkl_fft.patch # [not nomkl]
    - intel_distribution.patch        # [not nomkl]
    - intel_umath_optimizations.patch # [not nomkl]
    - intel_mkl_mem_all.patch         # [not nomkl]
    - intel_init_mkl.patch            # [blas_impl == 'mkl' and (not win or vc>=14)]
    - intel_mkl_random.patch          # [not nomkl]
    # patch up MKL patches
    - 0001-Remove-ICC-specific-flags.patch # [not nomkl]
    - 0002-Remove-np.invsqrt.patch         # [not nomkl]
    - 0003-Rewrite-inlining.patch          # [not nomkl]


    # patch sequence switched as it is easier to apply smaller patches than
    # larger ones to the changes above!
    - 0002-simplify-arch-flags.patch # [osx]
    # customize gfortran executable that gets looked for to use our GFORTRAN env var
    - 0003-use-gfortran-from-env-variable.patch
    # Seems to be an issue with case sensitivity and Windows filesystem permission errors.
    - 0004-fix-windows-case-sensitivity.patch   # [win]
    - 0006-disable-memmap-filename-test-due-to-CI-link-confusio.patch  # [win]

build:
  number: 0
  skip: True  # [blas_impl == 'openblas' and win]
  # conda 4.4+ can use this
  requires_features:
    blas: {{ blas_impl }}
  # this is for conda 4.3 and below
  features:
    - nomkl    # [x86 and blas_impl != 'mkl']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    # libgcc-ng should be a dependecy of libgfortran
    # until this is fixed add libgcc explicitly
    - libgcc-ng         # [linux and blas_impl == 'openblas']
  host:
    - cython
    - python
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - setuptools
  run:
    - python
    # openblas or mkl runtime included with run_exports
    - mkl_fft # [blas_impl == 'mkl']
    - mkl_random # [blas_impl == 'mkl']


test:
  requires:
    - nose
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - nomkl  # [x86 and blas_impl != 'mkl']
  commands:
    - f2py -h
    - python -c "import numpy; numpy.show_config()"
    - conda inspect linkages -p $PREFIX numpy  # [not win]
    - conda inspect objects -p $PREFIX numpy  # [osx]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  description: |
    NumPy is the fundamental package needed for scientific computing with Python.
  doc_url: https://docs.scipy.org/doc/numpy-1.14.0/reference/
  dev_url: https://github.com/numpy/numpy
  dev_source_url: https://github.com/numpy/numpy/tree/master/doc

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
